In [1]:
import numpy as np
puzzle = [[1,0,0,0,0,7,0,9,0],
          [0,3,0,0,2,0,0,0,8],
          [0,0,9,6,0,0,5,0,0],
          [0,0,5,3,0,0,9,0,0],
          [0,1,0,0,8,0,0,0,2],
          [6,0,0,0,0,4,0,0,0],
          [3,0,0,0,0,0,0,1,0],
          [0,4,0,0,0,0,0,0,7],
          [0,0,7,0,0,0,3,0,0]]
def tries(r,c,t):
  global puzzle
  for i in range(9): #check row
    if puzzle[r][i] == t:
      return False
  for i in range(9): #check column
    if puzzle[i][c] == t:
      return False
  #check 3x3 box
  box_r = (r//3)*3
  box_c = (c//3)*3
  for i in range(0,3):
    for j in range(0,3):
      if puzzle[box_r +i][box_c + j] == t:
        return False
  return True
def solver():
  global puzzle
  for r in range(9):
    for c in range(9):
      if puzzle[r][c] == 0:
        for t in range(1,10):
          if tries(r,c,t) == True:
            puzzle[r][c] = t
            solver()
            puzzle[r][c] = 0
        return 
  print(np.array(puzzle))
  input('Solve again?')
solver()

[[1 6 2 8 5 7 4 9 3]
 [5 3 4 1 2 9 6 7 8]
 [7 8 9 6 4 3 5 2 1]
 [4 7 5 3 1 2 9 8 6]
 [9 1 3 5 8 6 7 4 2]
 [6 2 8 7 9 4 1 3 5]
 [3 5 6 4 7 8 2 1 9]
 [2 4 1 9 3 5 8 6 7]
 [8 9 7 2 6 1 3 5 4]]
Solve again?


In [2]:
import timeit
time_code = """
#input code here
#global keying ruins time test, comment out global keys in function if possible
import numpy as np
puzzle = [[1,0,0,0,0,7,0,9,0],
          [0,3,0,0,2,0,0,0,8],
          [0,0,9,6,0,0,5,0,0],
          [0,0,5,3,0,0,9,0,0],
          [0,1,0,0,8,0,0,0,2],
          [6,0,0,0,0,4,0,0,0],
          [3,0,0,0,0,0,0,1,0],
          [0,4,0,0,0,0,0,0,7],
          [0,0,7,0,0,0,3,0,0]]
def tries(r,c,t):
  #global puzzle
  for i in range(9): #check row
    if puzzle[r][i] == t:
      return False
  for i in range(9): #check column
    if puzzle[i][c] == t:
      return False
  #check 3x3 box
  box_r = (r//3)*3
  box_c = (c//3)*3
  for i in range(0,3):
    for j in range(0,3):
      if puzzle[box_r +i][box_c + j] == t:
        return False
  return True
def solver():
  #global puzzle
  for r in range(9):
    for c in range(9):
      if puzzle[r][c] == 0:
        for t in range(1,10):
          if tries(r,c,t) == True:
            puzzle[r][c] = t
            solver()
            puzzle[r][c] = 0
        return 
  #for row in puzzle:
    #print(row)
  #print(np.array(puzzle))
  #input('Solve again?')
solver()
"""
elapsed_time = timeit.timeit(time_code,number=1)
print(elapsed_time)
print((elapsed_time)/1)

0.35819620000000185
0.35819620000000185
